### ISSUE TITLE
Error while installing/building(?) tensorboardX

### ISSUE THREAD

**Issue by praeludiumOrbis** [peterlazzarino/jukebox#1]
I guess you're not really responsible for this as the same thing happens with OpenAI's fork, but I'm getting [this](https://myangel.aku.lu/C6uHPD.txt) output when trying to install tensorboardX with `pip install ./tensorboardX` and I don't know what to do with it. It would be nice if you could help me out with this :/

**Comment by jeffcrouse** [comment]
Huge thanks to peter for starting this fork. 

I am also having this issue.

**Comment by praeludiumOrbis** [comment]
> I am also having this issue.

In case you haven't resolved it yet, here's the solution:
https://github.com/openai/jukebox/issues/53#issuecomment-627117151 

With that in mind, I'll close this issue now.
